meta:
    num_tasks: 100
    n_way: 5
    k_shot: 1
    q_queries: 15
    inner_steps: 10
    inner_lr: 0.001
    outer_lr: 0.001
    epochs: 300

data:
    image_size: 224
    json_base: data/filelists_clean/base.json
    json_val: data/filelists_clean/val.json
    json_test: data/filelists_clean/novel.json
    root_dir: data/miniImageNet

training:
    batch_size: 4
    log_every: 10
    save_every: 5
    checkpoint_dir: model/
